
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Oct 18 00:35:38 CEST 2019
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREATERTHAN = 37;
  public static final int CONST = 17;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int CONTINUE = 27;
  public static final int INTERFACE = 24;
  public static final int LESSTHANOREQUALTO = 40;
  public static final int MINUS = 42;
  public static final int FOR = 25;
  public static final int RPAREN = 7;
  public static final int GREATERTHANOREQUALTO = 38;
  public static final int AND = 32;
  public static final int OPTARG = 49;
  public static final int EQUALTO = 35;
  public static final int LESSTHAN = 39;
  public static final int OR = 31;
  public static final int COMMA = 8;
  public static final int CLASS = 21;
  public static final int INC = 29;
  public static final int DIV = 44;
  public static final int PLUS = 41;
  public static final int IF = 15;
  public static final int THIS = 48;
  public static final int DOT = 34;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int EQUAL = 11;
  public static final int NEW = 33;
  public static final int error = 1;
  public static final int MOD = 45;
  public static final int NUMBER = 13;
  public static final int BREAK = 26;
  public static final int IDENT = 14;
  public static final int VOID = 12;
  public static final int LBRACK = 19;
  public static final int TIMES = 43;
  public static final int LBRACE = 3;
  public static final int ELSE = 16;
  public static final int ENUM = 18;
  public static final int READ = 28;
  public static final int RBRACK = 20;
  public static final int CHARCONST = 46;
  public static final int NOTEQUALTO = 36;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 47;
  public static final int EXTENDS = 22;
  public static final int PROG = 2;
  public static final int DEC = 30;
  public static final int IMPLEMENTS = 23;
  public static final int PRINT = 9;
}

